[manager]
prepend_keymap = [
  { on = ["d"], run = "yank --cut", desc = "Cut" },
  { on = ["D"], run = "remove",     desc = "Delete" },
  { on = ["a"], run = "rename --empty=ext --cursor=end",     desc = "Rename" },
  { on = ["i"], run = "rename --empty=stem --cursor=start",     desc = "Rename" },
  { on = ["%"], run = "create",     desc = "Create file/dir (if ends with /)" },
  { on = ["t"], run = "create",     desc = "Create file/dir (if ends with /)" },
  { on = ["m"], run = "create",     desc = "Create file/dir (if ends with /)" },
  { on = ["w"], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  { on = ["<C-f>"], run = "plugin fzf", desc = "File/dir search" },
  { on = ["<C-p>"], run = "plugin fzf", desc = "File/dir search" },

  # Plugins
  { on = ["l"], run  = "plugin --sync smart-enter",  desc = "Enter the child directory, or open the file"},
  { on = ["p"], run  = "plugin --sync smart-paste",  desc = "Paste into the hovered directory or CWD"},
]
